# Generated by Django 3.2.15 on 2022-09-09 15:13

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSteps',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('order_step', models.CharField(max_length=255, unique=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='orders.order')),
                ('order_start_date', models.DateField()),
                ('order_end_date', models.DateField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='ordersteps',
            constraint=models.CheckConstraint(check=models.Q(('order_start_date__lt', django.db.models.expressions.F('order_end_date'))), name='start_date_before_end_date'),
        ),
    ]
