# Generated by Django 3.2.15 on 2022-09-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20220909_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeLinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_time_code', models.CharField(max_length=20)),
                ('expiry_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
